version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    container_name: "n8n"
    ports:
      - 5678:5678
    volumes:
      - ./:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    restart: unless-stopped
